app = "petfinder-lapixx"   # ‚Üê change to your name if you want

[build]
  builder = "paketobuildpacks/builder:base"

[[mounts]]
  source = "petdata"
  destination = "/data"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[statics]]
  guest_path = "/data"
  url = "/files/"
